{
  "name": "Feature Request",
  "description": "Submit a request for a new feature",
  "labels": ["feature"],
  "body": [
    {
      "type": "textarea",
      "attributes": {
        "label": "Describe the feature",
        "description": "A clear and concise description of what the feature should do"
      },
      "validations": {
        "required": true
      }
    },
    {
      "type": "textarea",
      "attributes": {
        "label": "User Story",
        "description": "Describe the feature from the perspective of the user",
        "placeholder": "As a [type of user], I want to [perform some task] so that I can [achieve some goal]"
      },
      "validations": {
        "required": false
      }
    },
    {
      "type": "textarea",
      "attributes": {
        "label": "Benefits",
        "description": "Explain the benefits of the feature and why it should be added"
      },
      "validations": {
        "required": false
      }
    },
    {
      "type": "textarea",
      "attributes": {
        "label": "Additional Information",
        "description": "Add any additional information or context that might be useful"
      },
      "validations": {
        "required": false
      }
    }
  ]
}
